# Generated by Django 3.2.6 on 2021-08-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
