# Generated by Django 3.2.6 on 2021-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_profile_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment',
            field=models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid')], max_length=10),
        ),
    ]
