# Generated by Django 3.2.6 on 2021-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_profile_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_subscrible',
            field=models.CharField(choices=[('SUBSCRIBE', 'subscribe'), ('UNSUBSCRIBE', 'unsubscribe')], default='unsubscribe', max_length=15),
        ),
    ]
