# Generated by Django 3.2.6 on 2021-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_profile_status_subscrible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment',
            field=models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_subscrible',
            field=models.BooleanField(default=False),
        ),
    ]
