# Generated by Django 3.2.6 on 2021-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20210829_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_subscrible',
            field=models.BooleanField(default=False),
        ),
    ]
