# Generated by Django 3.2.6 on 2021-08-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_alter_profile_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status_subscrible',
        ),
    ]
